### ISSUE TITLE
Verify full Unicode support

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-abi#2]
Should support this already, but should test to make sure.

**Comment by thinkloop** [comment]
Test with `☃` and `€`.
The first is 2-bytes in UTF-8, the second is 3 bytes in UTF-8 and 2 bytes in UTF-16.
The first also doesn't render in many fonts.

**Comment by tinybike** [comment]
Fixed in add7e12ec37cc775a2adaa196a876ae607b45bc5.
